# [✓] Hello There, This Is Main Configuration File Of DungeonX Plugin
# [×] Don't Edit Any Config Text Or Your Server Will Crashed
# [✓] Config Begin !

# [✓] Type The Delay Time Which The Block Will Regen After Broken By A Player !
# [✓] Default Time Is 6
"delay": 6
# [✓] Type The World Name Where The Plugin Will Work !
# [✓] Default Level Name Is "world"
"levelname": "world"
# [✓] Now Here You Can Customize The Block If They Can Regen Or Not
"coal_ore": true
"iron_ore": true
"gold_ore": true
"diamond_ore": true
"emerald_ore": true
"quartz_ore": true
"lapis_ore": true
"carrot_block": true
"potato_block": true
"wheat_block": true
"spruce_wood": true
"birch_wood": true
"dark_oak_wood": true
"acacia_wood": true
"jungle_wood": true

# [✓] Make Sure To Give A Star On This Plugin In GitHub !
